function skillsMember() {
  var skills = [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Node',
    'MongoDB',
    'Express',
    'Python',
    'Django',
    'Ruby',
    'Ruby on Rails',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'Java',
    'Spring',
    'C++',
    'C#',
    'PHP',
    'WordPress',
    'Shopify',
    'Magento',
    'Swift',
    'Objective-C',
    'Kotlin',
    'Flutter',
    'Dart',
    'Go',
    'Rust',
    'Perl',
    'Scala',
    'Haskell',
    'Clojure',
    'F#',
    'R',
    'Julia',
    'MATLAB',
    'SAS',
    'SPSS',
    'Stata',
    'Excel',
    'Tableau',
    'Power BI',
    'QlikView',
    'Looker',
    'Sisense',
    'Google Data Studio',
    'Data Studio',
    'Data Warehousing',
    'ETL',
    'Data Modeling',
    'Data Mining',
    'Data Analysis',
    'Data Visualization',
    'Statistics',
    'Machine Learning',
    'Deep Learning',
    'Neural Networks',
    'Natural Language Processing',
    'Computer Vision',
    'Big Data',
    'Hadoop',
    'Spark',
    'Kafka',
    '